# Generated by Django 3.1.2 on 2020-10-17 01:22

from django.db import migrations

from users.models import Profile


NEW_USERS = [
    ('kulibin@mail.ru', '1', 'author'),
    ('vlasov@mail.ru', '2', 'moderator')
]


def create_users(apps, schema_editor):
    """Создание пользователей и их групп."""
    #Profile = apps.get_model('users', 'Profile')
    Group = apps.get_model('auth', 'Group')
    for email, password, group in NEW_USERS:
        group, _ = Group.objects.get_or_create(
            name=group
        )
        profile = Profile.objects.create_user(
            email,
            password
        )
        profile.groups.add(group.id)


def remove_users(apps, schema_editor):
    """Удаление пользователей и груп."""
    Profile = apps.get_model('users', 'Profile')
    Group = apps.get_model('auth', 'Group')
    for email, password, group in NEW_USERS:
        Group.objects.filter(name=group).delete()
        Profile.objects.filter(email=email).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RunPython(create_users, remove_users)
    ]
