# Generated by Django 3.1.2 on 2020-10-16 23:34

import os

from django.conf import settings
from django.core.management import call_command
from django.db import migrations


def load_obscene_word(apps, schema_editor):
    """Загрузка недопустимых слов."""
    fixture_path = os.path.join(
        settings.BASE_DIR,
        'verification',
        'fixtures',
        'obscene_words.json'
    )
    call_command('loaddata', fixture_path)


def remove_obscene_word(apps, schema_editor):
    """Откат загрузки недопустимых слов."""
    apps.get_model('verification', 'ObsceneWord').objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_obscene_word, remove_obscene_word)
    ]
