# Generated by Django 3.1.2 on 2020-10-17 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0002_auto_20201016_2334'),
    ]

    operations = [
        migrations.CreateModel(
            name='BanContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=254, verbose_name='URL запрещенного ресурса')),
            ],
        ),
    ]
