# Generated by Django 3.1.2 on 2020-10-17 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='level',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='education.level', verbose_name='Цель/Уровень'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='level',
            name='module',
        ),
        migrations.AddField(
            model_name='level',
            name='module',
            field=models.ForeignKey(blank=True, default='2', on_delete=django.db.models.deletion.CASCADE, to='education.module', verbose_name='Модули'),
            preserve_default=False,
        ),
    ]
