# Generated by Django 3.1.2 on 2020-10-17 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_auto_20201017_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.module', verbose_name='Модули'),
        ),
        migrations.AlterField(
            model_name='task',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.level', verbose_name='Цель/Уровень'),
        ),
    ]
