# Generated by Django 3.1.2 on 2020-10-17 14:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('education', '0003_auto_20201017_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Владелец модуля'),
        ),
        migrations.AlterField(
            model_name='module',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='module',
            name='cover_picture',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Обложка модуля'),
        ),
        migrations.AlterField(
            model_name='module',
            name='general_concept',
            field=models.TextField(blank=True, null=True, verbose_name='Общий замысел модуля'),
        ),
        migrations.AlterField(
            model_name='module',
            name='possible_difficulties',
            field=models.TextField(blank=True, null=True, verbose_name='Возможные трудности, ложные представления и способы их преодоления'),
        ),
        migrations.AlterField(
            model_name='module',
            name='small_picture',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Картинка для списка'),
        ),
        migrations.AlterField(
            model_name='module',
            name='typical_distribution',
            field=models.TextField(blank=True, null=True, verbose_name='Типовое распределение заданий по\xa0урокам'),
        ),
        migrations.AlterField(
            model_name='module',
            name='work_hours',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)], verbose_name='Трудоемкость'),
        ),
        migrations.AlterField(
            model_name='task',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
    ]
