# Generated by Django 3.1.2 on 2020-10-17 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_auto_20201017_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='education.module', verbose_name='Модули'),
        ),
    ]
