# Generated by Django 3.1.2 on 2020-10-17 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_auto_20201017_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='education.level', verbose_name='Цель/Уровень'),
        ),
    ]
