# Generated by Django 3.1.2 on 2020-10-18 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_auto_20201017_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='cover_picture',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Обложка модуля'),
        ),
        migrations.AlterField(
            model_name='module',
            name='small_picture',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Картинка для списка'),
        ),
    ]
